def groupName="expositor"
def hostExposePort=8083
node { 
   def mvnHome

   stage('Preparation') { 
      git 'https://github.com/ricardogar/spring-boot-calculator.git'
      mvnHome = tool 'MAVEN3'
   }
      stage('Build') {      
      sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
   }
   
   stage('QA Analysis') {
      sh "'${mvnHome}/bin/mvn' sonar:sonar -Dsonar.host.url=http://52.200.168.109:9000 -Dsonar.projectName=${groupName} -Dsonar.projectKey=${groupName}"
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
   
   stage('Deployment') {
      sh "chmod +x devops/deploy.sh"
      def result=sh(script: "devops/deploy.sh ${hostExposePort}",returnStdout: true)
      echo "result: "+result
   }
}
