def groupName="expositor"
def hostExposePort=8083
node { 
   def mvnHome="/usr/share/maven"

   stage('Preparation') { 
      git 'https://github.com/ricardogar/spring-boot-calculator.git'
   }
   stage('Build') {    
       sh "'${mvnHome}/bin/mvn' package"         
   }
   
  stage('QA Analysis') {
  }
   stage('Results') {
      
      archive 'target/*.jar'
   }
   
   stage('Deployment') {
      sh "chmod +x devops/deploy.sh"
      def result=sh(script: "devops/deploy.sh ${hostExposePort}",returnStdout: true)
      echo "result: "+result
   }
}
